### ISSUE TITLE
Wavey Capes mod support

### ISSUE THREAD

**Issue by Romz24** [jbredwards/Baubley-Elytra-Mod#1]
When using this mod, I have 2 raincoats displayed. Can you add support for this mod so that there is no visual bug?

Mod link: https://www.curseforge.com/minecraft/mc-mods/waveycapes
![2022-08-19_21 23 15](https://user-images.githubusercontent.com/2458113/185684411-046d7efc-3899-4850-ab67-db59c1bcc674.png)
![2022-08-19_21 23 33](https://user-images.githubusercontent.com/2458113/185684426-4f11591a-c411-477e-b483-b2b6e2e2d4f6.png)

**Comment by jbredwards** [comment]
this is an issue that also happens without my mod installed, it's a problem on their side
