### ISSUE TITLE
Elytra Soulbound enchant not working in Bauble slot

### ISSUE THREAD

**Issue by MineCrak** [jbredwards/Baubley-Elytra-Mod#2]
Baubley-Elytra-v1.2b-mc1.12.2
CoFHCore-1.12.2-4.6.3.27-universal
Minecraft 1.12.2
Forge 2860

Soulbound Enchantment from CoFHCore.

An Elytra with the Soulbound enchantment does work fine when equipped in the normal body slot but does not when equipped in the bauble slot. 

When the Elytra is in the bauble slot during death, the Elytra remains at the death location. 
When the same Elytra is in the normal body chest slot it returns to spawn with the player, though goes into inventory as is normal for Soulbound. 

I really want to replace Colytra with your mods, but my players are addicted to both Elytras and the Soulbound Enchantment. If this can be fixed you would be loved by everyone on my server. 

Thank you

**Comment by jbredwards** [comment]
This is an issue with CoFHCore's lack of Baubles integration, added a fix from my side in v1.3
