### ISSUE TITLE
Server kick [v1.3]

### ISSUE THREAD

**Issue by Romz24** [jbredwards/Baubley-Elytra-Mod#3]
I updated the mod on the server and client, now when I try to open the Baubley inventory, I just get kicked out of the game.

Server log:
https://pastebin.com/F1nB87gq

![image](https://user-images.githubusercontent.com/2458113/216988239-5aad4f58-68b9-485e-86ca-8db922e4e2bc.png)

**Comment by Romz24** [comment]
the same error occurs if you try to go to a server where your mod is not installed

**Comment by jbredwards** [comment]
pastebin is saying the link is private or waiting for a moderator, can you link it using https://mclo.gs instead?

**Comment by Romz24** [comment]
https://mclo.gs/E27dpHQ

**Comment by jbredwards** [comment]
fixed in v1.3.1, p.s. this mod is needed on both the server and client to work
